# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


branches:
    only:
        - master
matrix:
    include:
        - os: linux
          r: release
          r_packages: pkgdown
          bioc_packages: RBGL, graph
          after_success: Rscript -e 'covr::codecov()'
          deploy:
            provider: script
            script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
            skip_cleanup: true
            on: 
                all_branches: true
        - os: linux
          r: oldrel 
          bioc_packages: RBGL, graph
        - os: linux
          r: devel
          bioc_packages: RBGL, graph
          before_install: export _R_CHECK_CRAN_INCOMING_=true
        - os: osx
          r: release
          bioc_packages: RBGL, graph
        - os: osx
          brew_packages: libgit2
          bioc_packages: RBGL, graph
          r: oldrel

