# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

bioc_packages:
    - RBGL
    - graph

branches:
    only:
        - master
matrix:
    include:
        - os: linux
          r: release
          r_packages: pkgdown
          after_success: Rscript -e 'covr::codecov()'
          before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
          deploy:
            provider: script
            script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
            skip_cleanup: true
        - os: linux
          r: oldrel 
        - os: linux
          r: devel
          before_install: export _R_CHECK_CRAN_INCOMING_=true
        - os: osx
          r: release
        - os: osx
          brew_packages: libgit2
          r: oldrel

